site:
  title: Gloomhaven Enhanced
content:
  sources:
    - url: https://github.com/gloomhaven-tts-enhanced/public-scripts
      start_path: docs/content/customContent
      branches: HEAD
    - url: https://github.com/gloomhaven-tts-enhanced/public-scripts
      start_path: docs/content/development
      branches: HEAD
    - url: https://github.com/gloomhaven-tts-enhanced/public-scripts
      start_path: docs/content/mod
      branches: HEAD
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    experimental: true
