name: Publish to GitHub Pages
on:
  push:
    branches: [main]
    paths:
      - "docs/*"
  workflow_dispatch:    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build UI bundle
      working-directory: docs/ui
      run: npm install && npm run build
    - name: Install Antora
      run: npm install antora
    - name: Generate Site
      run: npx antora docs/antora-playbook.yml
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/site
